name: ROCM gfx1200 Build
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
    - name: Build
      run: |
        echo "Build would go here"
